### ISSUE TITLE
Provisioning with tlsSkipVerify not activating the TLS skip option

### ISSUE THREAD

**Issue by joe-macmillan** [chaos-mesh/chaos-mesh-datasource#63]
**Issue Description:**

On grafana/grafana:10.3.3, provisioning the Chaos Mesh data source with the following YAML configuration does not activate the "Skip TLS Verify" toggle in the data source configuration section:

```yaml
- name: 'Chaos Mesh'
  type: 'chaosmeshorg-datasource'
  access: proxy
  url: https://<chaose-dashboard-url>
  uid: ChaosMeshDataSource
  jsonData:
    tlsSkipVerify: true
  version: 1
```

Neither does the following configuration work:

```yaml
- name: 'Chaos Mesh'
  type: 'chaosmeshorg-datasource'
  access: proxy
  url: https://<chaose-dashboard-url>
  uid: ChaosMeshDataSource
  secureJsonData:
    tlsSkipVerify: true
  version: 1
```
Other values, such as `name` and `url`, seem to be provisioning correctly. However, if I configure the data source manually on the Grafana dashboard, the "Skip TLS Verify" toggle works fine. I expected the provisioning configuration to be as effective as the manual configuration.

Is there a way to know why this `tlsSkipVerify` provisioning does not work? Has this feature been tested in provisioning?
Alternatively, is there a comprehensive list of configuration settings for this data source that I can refer to?
